### ISSUE TITLE
Whitelist support

### ISSUE THREAD

**Issue by alecmev** [rt2zz/redux-persist-crosstab#2]
Was about to request whitelist support in the parent project, but @grabbou [beat me to it](https://github.com/rt2zz/redux-persist/issues/9) :)

In the linked issue you said:

> My hesitation is that I have yet to see an app that would whitelist more than it would blacklist.

I think it's the opposite in this case, since cross-tab syncing is so sensitive to race conditions (at least with the current implementation). Mimicking `redux-persist` in this matter is the obvious solution.

**Comment by grabbou** [comment]
Ha! +1

**Comment by rt2zz** [comment]
just added whitelist https://github.com/rt2zz/redux-persist-crosstab/commit/17d659ff06afe4428cd71baeed4c62d5f83ece51

I have not tested it at all, so not going to npm publish yet. If possible install from git and let me know if that works for you.

**Comment by alecmev** [comment]
I don't have any frontend tests yet myself, but this seems to be working fine in my setup. The code is logically sound too :) Should be okay to publish. Thanks.

**Comment by rt2zz** [comment]
just published 1.0.1
